services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./flow2and4:/app/flow2and4
      - ./instance:/app/instance
    expose:
      - "8000"

  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - web
