services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    expose:
      - "8000"
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

