services:
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.cert.conf:/etc/nginx/nginx.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: certonly --reinstall --webroot --webroot-path=/var/www/certbot --email flow2kudo@naver.com --agree-tos --no-eff-email -d faduck.flow2and4.me # multiple `-d` flag not working. so... I manually updated 1 domain 3 subdomains !!
    depends_on:
      - nginx
