services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./flow2and4
        target: /app/flow2and4
      - type: bind
        source: ./instance
        target: /app/instance
    expose:
      - "8000"
  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  worker:
    container_name: worker
    environment:
      - CELERY_MODE=prodlike
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./flow2and4
        target: /app/flow2and4
      - type: bind
        source: ./instance
        target: /app/instance
    command: celery -A make_celery worker --loglevel INFO
    depends_on:
      - redis
