services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./flow2and4:/app/flow2and4
      - ./instance:/app/instance
    expose:
      - "8000"

  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command:
      [
        "certonly",
        "--reinstall",
        "--webroot",
        "--webroot-path=/var/www/certbot",
        "--email",
        "flow2kudo@naver.com",
        "--agree-tos",
        "--no-eff-email",
        "-d",
        "csduck.flow2and4.me",
        "-d",
        "pyduck.flow2and4.me",
        "-d",
        "faduck.flow2and4.me",
        "-d",
        "flow2and4.me"
      ]
    depends_on:
      - nginx
