services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - ./flow2and4:/app/flow2and4
      - ./instance:/app/instance
    expose:
      - "8000"

  nginx:
    container_name: nginx
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - web

  redis:
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  worker:
    container_name: worker
    environment:
      - CELERY_MODE=prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - type: bind
        source: ./flow2and4
        target: /app/flow2and4
      - type: bind
        source: ./instance
        target: /app/instance
    command: celery -A make_celery worker --loglevel INFO
    depends_on:
      - redis
