"""empty message

Revision ID: 2565a0944267
Revises: 7c4a310743bb
Create Date: 2023-05-18 11:17:33.753403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2565a0944267'
down_revision = '7c4a310743bb'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_value', sa.String(), nullable=True))
        batch_op.drop_constraint('uq_notification_user_id_notification_type_notification_target_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_notification_user_id_notification_type_notification_value_notification_target_id'), ['user_id', 'notification_type', 'notification_value', 'notification_target_id'])

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_notification_user_id_notification_type_notification_value_notification_target_id'), type_='unique')
        batch_op.create_unique_constraint('uq_notification_user_id_notification_type_notification_target_id', ['user_id', 'notification_type', 'notification_target_id'])
        batch_op.drop_column('notification_value')

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

