"""empty message

Revision ID: 3ea8bd6e1bfa
Revises: 8321c9b0599d
Create Date: 2023-05-16 01:18:14.414996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea8bd6e1bfa'
down_revision = '8321c9b0599d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_reaction_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reaction')),
    sa.UniqueConstraint('user_id', 'target', 'target_id', 'code', name=op.f('uq_reaction_user_id_target_target_id_code'))
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_target'), ['target'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_user_id'), ['user_id'], unique=False)
        batch_op.create_index('target', ['target_id'], unique=False)

    op.drop_table('post_comment_reaction')
    op.drop_table('answer_reaction')
    op.drop_table('answer_comment_reaction')
    op.drop_table('post_reaction')
    op.drop_table('question_reaction')
    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_question_reaction_question_id_question'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_question_reaction'),
    sa.UniqueConstraint('user_id', 'question_id', 'code', name='uq_question_reaction_user_id_question_id_code')
    )
    op.create_table('post_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_post_reaction_post_id_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post_reaction'),
    sa.UniqueConstraint('user_id', 'post_id', 'code', name='uq_post_reaction_user_id_post_id_code')
    )
    op.create_table('answer_comment_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['answer_comment.id'], name='fk_answer_comment_reaction_comment_id_answer_comment'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_comment_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_answer_comment_reaction')
    )
    op.create_table('answer_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('answer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_reaction_answer_id_answer'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_answer_reaction')
    )
    op.create_table('post_comment_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], name='fk_post_comment_reaction_comment_id_post_comment'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_comment_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post_comment_reaction')
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_index('target')
        batch_op.drop_index(batch_op.f('ix_reaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_reaction_target'))

    op.drop_table('reaction')
    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

