"""empty message

Revision ID: 5c994cf061ba
Revises: 116a148da1ae
Create Date: 2023-05-17 11:05:52.864654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c994cf061ba'
down_revision = '116a148da1ae'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_notification_target_type')
        batch_op.drop_index('ix_notification_user_id_notification_notification_type_notification_notification_target_type')
        batch_op.drop_constraint('uq_notification_user_id_notification_type_notification_target_type_notification_target_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_notification_user_id_notification_notification_type'), ['user_id', 'notification_type'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_notification_user_id_notification_type_notification_target_id'), ['user_id', 'notification_type', 'notification_target_id'])
        batch_op.drop_column('notification_target_type')

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_target_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_notification_user_id_notification_type_notification_target_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_notification_user_id_notification_notification_type'))
        batch_op.create_unique_constraint('uq_notification_user_id_notification_type_notification_target_type_notification_target_id', ['user_id', 'notification_type', 'notification_target_type', 'notification_target_id'])
        batch_op.create_index('ix_notification_user_id_notification_notification_type_notification_notification_target_type', ['user_id', 'notification_type', 'notification_target_type'], unique=False)
        batch_op.create_index('ix_notification_notification_target_type', ['notification_target_type'], unique=False)

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

