"""empty message

Revision ID: 774ecccef7da
Revises: bc6a96c9d566
Create Date: 2023-05-15 15:43:21.315920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774ecccef7da'
down_revision = 'bc6a96c9d566'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vote_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_vote_post_comment_id_post_comment', type_='foreignkey')
        batch_op.drop_constraint('fk_vote_answer_id_answer', type_='foreignkey')
        batch_op.drop_column('post_comment_id')
        batch_op.drop_column('answer_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('answer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('post_comment_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_vote_answer_id_answer', 'answer', ['answer_id'], ['id'])
        batch_op.create_foreign_key('fk_vote_post_comment_id_post_comment', 'post_comment', ['post_comment_id'], ['id'])
        batch_op.create_foreign_key('fk_vote_post_id_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

