"""empty message

Revision ID: 7c4a310743bb
Revises: 5c994cf061ba
Create Date: 2023-05-18 10:21:57.138665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4a310743bb'
down_revision = '5c994cf061ba'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_value', sa.String(), nullable=True))
        batch_op.drop_constraint('uq_user_action_user_id_action_type_target_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_action_user_id_action_type_action_value_target_id'), ['user_id', 'action_type', 'action_value', 'target_id'])

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_action_user_id_action_type_action_value_target_id'), type_='unique')
        batch_op.create_unique_constraint('uq_user_action_user_id_action_type_target_id', ['user_id', 'action_type', 'target_id'])
        batch_op.drop_column('action_value')

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

