"""empty message

Revision ID: e33e8f659f68
Revises: 118e7701ae51
Create Date: 2023-05-26 15:36:40.784487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33e8f659f68'
down_revision = '118e7701ae51'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_forgot_password_email_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vcode', sa.String(), nullable=False))
        batch_op.drop_column('vocde')

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_forgot_password_email_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vocde', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('vcode')

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

