"""empty message

Revision ID: e8532a812807
Revises: b86b0bbc92d2
Create Date: 2023-05-08 12:42:13.093172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8532a812807'
down_revision = 'b86b0bbc92d2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_post_tag', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assoc_post_tag_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_assoc_post_tag_tag_id_post_tag', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assoc_post_tag_post_id_post'), 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_assoc_post_tag_tag_id_post_tag'), 'post_tag', ['tag_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assoc_post_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assoc_post_tag_tag_id_post_tag'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_assoc_post_tag_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_assoc_post_tag_tag_id_post_tag', 'post_tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key('fk_assoc_post_tag_post_id_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

