"""empty message

Revision ID: f77366dad049
Revises: 3ea8bd6e1bfa
Create Date: 2023-05-16 01:21:30.978004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77366dad049'
down_revision = '3ea8bd6e1bfa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_reaction')
    op.drop_table('post_comment_reaction')
    op.drop_table('answer_comment_reaction')
    op.drop_table('post_reaction')
    op.drop_table('question_reaction')
    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_question_reaction_question_id_question'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_question_reaction'),
    sa.UniqueConstraint('user_id', 'question_id', 'code', name='uq_question_reaction_user_id_question_id_code')
    )
    op.create_table('post_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_post_reaction_post_id_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post_reaction'),
    sa.UniqueConstraint('user_id', 'post_id', 'code', name='uq_post_reaction_user_id_post_id_code')
    )
    op.create_table('answer_comment_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['answer_comment.id'], name='fk_answer_comment_reaction_comment_id_answer_comment'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_comment_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_answer_comment_reaction')
    )
    op.create_table('post_comment_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], name='fk_post_comment_reaction_comment_id_post_comment'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_comment_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post_comment_reaction')
    )
    op.create_table('answer_reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('answer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_reaction_answer_id_answer'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_reaction_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_answer_reaction')
    )
    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

