"""empty message

Revision ID: fa54b12dfa7e
Revises: 41193b2113d2
Create Date: 2023-05-10 11:13:26.894116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa54b12dfa7e'
down_revision = '41193b2113d2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post_comment')
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade_pyduck():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_post_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('vote_count', sa.INTEGER(), nullable=False),
    sa.Column('comment_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comment.id'], name='fk_post_comment_parent_id_post_comment'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='fk_post_comment_post_id_post'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_comment_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_post_comment')
    )
    # ### end Alembic commands ###


def upgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_faduck():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

