"""empty message

Revision ID: 4215738249aa
Revises: 8ac2951d6c66
Create Date: 2023-04-25 16:15:33.838635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4215738249aa'
down_revision = '8ac2951d6c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_email_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vcode', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_email_verification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_email_verification'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_email_verification')
    # ### end Alembic commands ###
